#!/bin/sh
#
# Copied from the engineyard dj bin
#
PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH
CURDIR=`pwd`

usage() {
  echo "Usage: $0 <appname> {start|stop} environment"
  exit 1
}

if [ $# -lt 3 ]; then usage; fi

if [ $4 ]; then
  NAME="_$4"
fi

if [ "`whoami`" != "root" ]; then
  logger -t `basename $0` -s "Must be run as root" 
  exit 1
fi

COMMAND="env QUEUE=* /usr/bin/rake RAILS_ENV=$3 -f /data/$1/current/Rakefile environment resque:work"
PID_FILE=/var/run/engineyard/resque/$1/resque$NAME.pid


if [ -d /data/$1/current ]; then
  RAIL_ROOT=/data/$1/current
  USER=`stat -c"%U" /data/$1/current`
  HOME="/home/$USER" ; export HOME

  cd /data/$1/current
  mkdir -p /var/run/engineyard/resque/$1

  # handle the second param, don't start if already existing
  case "$2" in
    start)
      cd /data/$1/current
      echo "Starting resque worker"
      if [ -f $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if [ -d /proc/$PID ]; then
          echo "resque worker is already running."
          exit 1
        fi
        rm -f $PID_FILE
      fi
      echo $$ > $PID_FILE;
      exec 2<&1 su -c"$COMMAND" $USER
      ;;
    stop)
      echo "Stopping resque worker"
      if [ -f $PID_FILE ]; then
        kill -15 `cat $PID_FILE` 2>/dev/null; true
      fi

      [ -e "$PIDFILE" ] && rm -f $PIDFILE
      ;;
    *)
      usage
      ;;
        esac
else
  echo "/data/$1/current doesn't exist."
  usage
fi
cd $CURDIR